import { FaCss3Alt } from "react-icons/fa6";
import {
  SiClaude,
  SiElementor,
  SiFigma,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGithubcopilot,
  SiHtml5,
  SiJavascript,
  SiLaravel,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostman,
  SiReact,
  SiShopify,
  SiTailwindcss,
  SiTypescript,
  SiWoocommerce,
  SiWordpress,
} from "react-icons/si";
import {
  TbApi,
  TbBrandOpenai,
  TbBrandVscode,
  TbBuildingStore,
  TbCloud,
  TbDatabase,
  TbShieldLock,
  TbSparkles,
} from "react-icons/tb";

import type { Locale } from "@/i18n/routing";
import type { SkillCategory } from "@/types";

const base = [
  {
    id: "frontend",
    skills: [
      { id: "react", icon: SiReact },
      { id: "nextjs", icon: SiNextdotjs },
      { id: "javascript", icon: SiJavascript },
      { id: "typescript", icon: SiTypescript },
      { id: "tailwind", icon: SiTailwindcss },
      { id: "html", icon: SiHtml5 },
      { id: "css", icon: FaCss3Alt },
      { id: "flutter", icon: SiFlutter },
    ],
  },
  {
    id: "backend",
    skills: [
      { id: "laravel", icon: SiLaravel },
      { id: "nodejs", icon: SiNodedotjs },
      { id: "firebase", icon: SiFirebase },
      { id: "restapis", icon: TbApi },
      { id: "auth", icon: TbShieldLock },
      { id: "databases", icon: TbDatabase },
      { id: "mysql", icon: SiMysql },
      { id: "sqlnosql", icon: TbDatabase },
    ],
  },
  {
    id: "cms",
    skills: [
      { id: "wordpress", icon: SiWordpress },
      { id: "woocommerce", icon: SiWoocommerce },
      { id: "shopify", icon: SiShopify },
      { id: "salla", icon: TbBuildingStore },
      { id: "6valley", icon: TbBuildingStore },
      { id: "easyorder", icon: TbBuildingStore },
    ],
  },
  {
    id: "tools",
    skills: [
      { id: "git", icon: SiGit },
      { id: "github", icon: SiGithub },
      { id: "postman", icon: SiPostman },
      { id: "vscode", icon: TbBrandVscode },
      { id: "figma", icon: SiFigma },
      { id: "elementor", icon: SiElementor },
      { id: "cloudhosting", icon: TbCloud },
    ],
  },
  {
    id: "ai",
    skills: [
      { id: "promptengineering", icon: TbSparkles },
      { id: "cursor", icon: TbBrandVscode },
      { id: "claude", icon: SiClaude },
      { id: "chatgpt", icon: TbBrandOpenai },
      { id: "copilot", icon: SiGithubcopilot },
    ],
  },
] as const;

const categoryLabels: Record<Locale, Record<string, string>> = {
  en: {
    frontend: "Frontend",
    backend: "Backend",
    cms: "CMS & eCommerce",
    tools: "Tools",
    ai: "AI",
  },
  ar: {
    frontend: "الواجهة الأمامية",
    backend: "الواجهة الخلفية",
    cms: "أنظمة إدارة المحتوى والتجارة الإلكترونية",
    tools: "الأدوات",
    ai: "الذكاء الاصطناعي",
  },
};

/** Brand/product names stay in Latin script in both locales; only generic skill words are translated. */
const skillNames: Record<Locale, Record<string, string>> = {
  en: {
    react: "React.js",
    nextjs: "Next.js",
    javascript: "JavaScript",
    typescript: "TypeScript",
    tailwind: "TailwindCSS",
    html: "HTML",
    css: "CSS",
    flutter: "Flutter",
    laravel: "Laravel",
    nodejs: "Node.js",
    firebase: "Firebase",
    restapis: "REST APIs",
    auth: "Authentication",
    databases: "Databases",
    mysql: "MySQL",
    sqlnosql: "SQL & NoSQL",
    wordpress: "WordPress",
    woocommerce: "WooCommerce",
    shopify: "Shopify",
    salla: "Salla",
    "6valley": "6Valley",
    easyorder: "EasyOrder",
    git: "Git",
    github: "GitHub",
    postman: "Postman",
    vscode: "VS Code",
    figma: "Figma",
    elementor: "Elementor",
    cloudhosting: "Cloud Hosting",
    promptengineering: "Prompt Engineering",
    cursor: "Cursor",
    claude: "Claude",
    chatgpt: "ChatGPT",
    copilot: "GitHub Copilot",
  },
  ar: {
    react: "React.js",
    nextjs: "Next.js",
    javascript: "JavaScript",
    typescript: "TypeScript",
    tailwind: "TailwindCSS",
    html: "HTML",
    css: "CSS",
    flutter: "Flutter",
    laravel: "Laravel",
    nodejs: "Node.js",
    firebase: "Firebase",
    restapis: "واجهات REST API",
    auth: "المصادقة (Authentication)",
    databases: "قواعد البيانات",
    mysql: "MySQL",
    sqlnosql: "SQL & NoSQL",
    wordpress: "WordPress",
    woocommerce: "WooCommerce",
    shopify: "Shopify",
    salla: "سلة (Salla)",
    "6valley": "6Valley",
    easyorder: "EasyOrder",
    git: "Git",
    github: "GitHub",
    postman: "Postman",
    vscode: "VS Code",
    figma: "Figma",
    elementor: "Elementor",
    cloudhosting: "استضافة سحابية",
    promptengineering: "هندسة الأوامر (Prompt Engineering)",
    cursor: "Cursor",
    claude: "Claude",
    chatgpt: "ChatGPT",
    copilot: "GitHub Copilot",
  },
};

export function getSkillCategories(locale: Locale): SkillCategory[] {
  return base.map((category) => ({
    id: category.id,
    label: categoryLabels[locale][category.id],
    skills: category.skills.map((skill) => ({
      name: skillNames[locale][skill.id],
      icon: skill.icon,
    })),
  }));
}
